class Item {
  String name;
  String image;
  String avatar;
  String description;

  Item({required this.name, required this.image, required this.avatar, required this.description});
}

final planets = [
  Item(name: 'Solar System', image: "solarSystem2", avatar: "Solar System",
      description: "The Solar System[b] is the gravitationally bound system of the Sun and the objects that orbit "
          "it.[9] It was formed 4.6 billion years ago when a dense region of a molecular cloud collapsed, forming "
          "the Sun and a protoplanetary disc. The Sun is an ordinary main sequence star that maintains a balanced "
          "equilibrium by the fusion of hydrogen into helium at its core, releasing this energy from its outer photosphere."
"The largest objects that orbit the Sun are the eight planets. In order from the Sun, they are four terrestrial"
          " planets (Mercury, Venus, Earth and Mars); two gas giants (Jupiter and Saturn); and two ice giants (Uranus and Neptune). "
          "All terrestrial planets have solid surfaces. Inversely, all giant planets do not have a definite surface, as they are mainly"
          " composed of gases and liquids. Over 99.86% of the Solar System's mass is in the Sun and nearly 90% of the remaining mass is in Jupiter and Saturn."
"There is a strong consensus among astronomers[c] that the Solar System has at least eight dwarf planets: Ceres, "
          "Pluto, Haumea, Quaoar, Makemake, Gonggong, Eris, and Sedna. There are a vast number of small Solar System bodies, such as asteroids, comets, "
          "centaurs, meteoroids, and interplanetary dust clouds. Some of these bodies are in the asteroid belt (between Mars's and Jupiter's orbit) and the Kuiper "
          "belt (just outside Neptune's orbit).[d] Six planets, six dwarf planets, and other bodies have orbiting natural satellites, which are commonly called 'moons'."
"The Solar System is constantly flooded by the Sun's charged particles, the solar wind, forming the heliosphere. "
          "Around 75–90 astronomical units, the solar wind is halted, resulting in the heliopause. This is the boundary of "
          "the Solar System to interstellar space. The outermost region of the Solar System is the theorized Oort cloud, the "
          "source for long-period comets, extending 2,000–200,000 astronomical units (0.032–3.2 light-years). The closest star "
          "to the Solar System, Proxima Centauri, is 4.25 light-years away. Both stars belong to the Milky Way galaxy."),
  Item(name: 'Sun', image: 'Sun', avatar: 'Sun',
      description: "The Sun is the star at the center of the Solar System. ""It is a massive, hot ball of plasma, inflated "
          "and heated by energy produced by nuclear fusion reactions at its "
      "core. Part of this energy is emitted from its surface as visible light, ultraviolet, and infrared radiation, providing "
          "most of the energy for life on Earth. The Sun has been an object of veneration in many cultures. It has been a central subject for astronomical research since antiquity."
"The Sun orbits the Galactic Center at a distance of 24,000 to 28,000 light-years.[9] From Earth, it is on average 1 AU "
      "(1.496×108 km) or about 8 light-minutes away. Its diameter is about 1,391,400 km (864,600 mi; 4.64 LS), 109 times that of Earth. "
          "Its mass is about 330,000 times that of Earth, making up about 99.86% of the total mass of the Solar System.[18] Roughly three-quarters of the Sun's"
          " mass consists of hydrogen (~73%); the rest is mostly helium (~25%), with much smaller quantities of heavier elements, including oxygen, carbon, neon, and iron.[19]"
"The Sun is a G-type main-sequence star (G2V), informally called a yellow dwarf, though its light is actually white. It "
      "formed approximately 4.6 billion[a][14][20] years ago from the gravitational collapse of matter within a region of "
      "a large molecular cloud. Most of this matter gathered in the center, whereas the rest flattened into an orbiting disk "
      "that became the Solar System. The central mass became so hot and dense that it eventually initiated nuclear fusion in "
      "its core. It is thought that almost all stars form by this process."),
  Item(name: 'Mercury', image: 'Mercury', avatar: 'Mercury',
      description: "Mercury is the first planet from the Sun and the smallest in the Solar System. In English, it is named "
          "after the Roman god Mercurius (Mercury), god of commerce and communication, and the messenger of the gods. Mercury "
          "is classified as a terrestrial planet, with roughly the same surface gravity as Mars. The surface of Mercury is "
          "heavily cratered, as a result of countless impact events that have accumulated over billions of years. Its largest "
          "crater, Caloris Planitia, has a diameter of 1,550 km (960 mi) and one-third the diameter of the planet (4,880 km or "
          "3,030 mi). Similarly to the Earth's Moon, Mercury's surface displays an expansive rupes system generated from thrust "
          "faults and bright ray systems formed by impact event remnants."
      "Mercury's sidereal year (88.0 Earth days) and sidereal day (58.65 Earth days) are in a 3:2 ratio. This relationship is "
          "called spin–orbit resonance, and sidereal here means 'relative to the stars'. Consequently, one solar day (sunrise "
          "to sunrise) on Mercury lasts for around 176 Earth days: twice the planet's sidereal year. This means that one side "
          "of Mercury will remain in sunlight for one Mercurian year of 88 Earth days; while during the next orbit, that side "
          "will be in darkness all the time until the next sunrise after another 88 Earth days."
      "Combined with its high orbital eccentricity, the planet's surface has widely varying sunlight intensity and temperature, "
          "with the equatorial regions ranging from −170 °C (−270 °F) at night to 420 °C (790 °F) during sunlight. Due to the "
          "very small axial tilt, the planet's poles are permanently shadowed. This strongly suggests that water ice could be "
          "present in the craters. Above the planet's surface is an extremely tenuous exosphere and a faint magnetic field that is "
          "strong enough to deflect solar winds. Mercury has no natural satellite."),
  Item(name: 'Venus', image: 'Venus', avatar: 'Venus',
      description: "Venus is the second planet from the Sun. It is a terrestrial planet and is the closest in mass "
          "and size to its orbital neighbour Earth. Venus is notable for having the densest atmosphere of the terrestrial "
          "planets, composed mostly of carbon dioxide with a thick, global sulfuric acid cloud cover. At the surface it has a"
          " mean temperature of 737 K (464 °C; 867 °F) and a pressure of 92 times that of Earth's at sea level. These conditions"
          " are extreme enough to compress carbon dioxide into a supercritical state close to Venus's surface."
      "Internally, Venus has a core, mantle, and crust. Venus lacks an internal dynamo, and its weak induced magnetosphere "
          "is instead caused by atmospheric interactions with the solar wind. Internal heat escapes through active volcanism, "
          "resulting in resurfacing instead of plate tectonics. Venus is one of two planets in the Solar System that have no "
          "moons.[20] Conditions perhaps favourable for life on Venus have been identified at its cloud layers. Venus may have "
          "had liquid surface water early in its history with a habitable environment,[21][22] before a runaway greenhouse effect "
          "evaporated any water and turned Venus into its present state.[23][24][25]"
      "The rotation of Venus has been slowed and turned against its orbital direction (retrograde) by the strong currents and drag of "
          "its atmosphere. It takes 224.7 Earth days for Venus to complete an orbit around the Sun, and a Venusian solar year is just "
          "under two Venusian days long. The orbits of Venus and Earth are the closest between any two Solar System planets, approaching "
          "each other in synodic periods of 1.6 years. Venus and Earth have the lowest difference in gravitational potential of any pair of "
          "Solar System planets. This allows Venus to be the most accessible destination and a useful gravity assist waypoint for interplanetary flights from Earth."),
  Item(name: 'Earth', image: 'Earth', avatar: 'Earth',
      description: "Earth is the third planet from the Sun and the only astronomical object known to harbor life. This is "
          "enabled by Earth being a water world, the only one in the Solar System sustaining liquid surface water. Almost all of "
          "Earth's water is contained in its global ocean, covering 70.8% of Earth's crust. The remaining 29.2% of Earth's crust is"
          " land, most of which is located in the form of continental landmasses within Earth's land hemisphere. Most of Earth's "
          "land is somewhat humid and covered by vegetation, while large sheets of ice at Earth's polar deserts retain more water "
          "than Earth's groundwater, lakes, rivers and atmospheric water combined. Earth's crust consists of slowly moving tectonic "
          "plates, which interact to produce mountain ranges, volcanoes, and earthquakes. Earth has a liquid outer core that generates a "
          "magnetosphere capable of deflecting most of the destructive solar winds and cosmic radiation."
"Earth has a dynamic atmosphere, which sustains Earth's surface conditions and protects it from most meteoroids and "
          "UV-light at entry. It has a composition of primarily nitrogen and oxygen. Water vapor is widely present in the atmosphere, forming "
          "clouds that cover most of the planet. The water vapor acts as a greenhouse gas and, together with other greenhouse gases in the atmosphere, "
          "particularly carbon dioxide (CO2), creates the conditions for both liquid surface water and water vapor to persist via the capturing of energy from "
          "the Sun's light. This process maintains the current average surface temperature of 14.76 °C (58.57 °F), at which water is liquid under atmospheric pressure. "
          "Differences in the amount of captured energy between geographic regions (as with the equatorial region receiving more sunlight than the polar regions) drive atmospheric "
          "and ocean currents, producing a global climate system with different climate regions, and a range of weather phenomena such as precipitation, allowing components such as nitrogen to cycle."
          "Earth is rounded into an ellipsoid with a circumference of about 40,000 km. It is the densest planet in "
          "the Solar System. Of the four rocky planets, it is the largest and most massive. Earth is about eight light-minutes away"
          " from the Sun and orbits it, taking a year (about 365.25 days) to complete one revolution. Earth rotates around its own axis in slightly less than a day ("
          "in about 23 hours and 56 minutes). Earth's axis of rotation is tilted with respect to the perpendicular to its orbital plane around the Sun, producing seasons."
          " Earth is orbited by one permanent natural satellite, the Moon, which orbits Earth at 384,400 km (1.28 light seconds) and is roughly a quarter as wide as Earth. The Moon's gravity helps "
          "stabilize Earth's axis, causes tides and gradually slows Earth's rotation. Tidal locking has made the Moon always face Earth with the same side."
  ),
  Item(name: 'Mars', image: 'Mars', avatar: 'Mars',
      description: "Mars is the fourth planet from the Sun. The surface of Mars is orange-red because it is covered in iron(III)"
          " oxide dust, giving it the nickname 'the Red Planet'.[21][22] Mars is among the brightest objects in Earth's sky and its high-contrast "
          "albedo features have made it a common subject for telescope viewing. It is classified as a terrestrial planet and is the second smallest of the Solar "
          "System's planets with a diameter of 6,779 km (4,212 mi). In terms of orbital motion, a Martian solar day (sol) is equal to 24.5 hours and a Martian solar year is equal"
          " to 1.88 Earth years (687 Earth days). Mars has two natural satellites that are small and irregular in shape: Phobos and Deimos."
      "The relatively flat plains in northern parts of Mars strongly contrast with the cratered terrain in southern highlands – "
          "this terrain observation is known as the Martian dichotomy. Mars hosts many enormous extinct volcanos (such as Olympus Mons, "
          "21.9 km or 13.6 mi tall) and one of the largest canyons in the Solar System (Valles Marineris, 4,000 km or 2,500 mi long). Geologically, the planet is fairly "
          "active with marsquakes trembling underneath the ground, dust devils sweeping across the landscape, and cirrus clouds. Carbon dioxide is substantially "
          "present in Mars's polar ice caps and thin atmosphere. During a year, there are large surface temperature swings on the surface between −78.5 °C (−109.3 °F) to "
          "5.7 °C (42.3 °F)[c] similar to Earth's seasons, as both planets have significant axial tilt."
 "Mars was formed approximately 4.5 billion years ago. During the Noachian period (4.5 to 3.5 billion years ago), Mars's surface"
          " was marked by meteor impacts, valley formation, erosion, and the possible presence of water oceans. The Hesperian period (3.5 to 3.3–2.9 billion years ago) "
          "was dominated by widespread volcanic activity and flooding that carved immense outflow channels."),
  Item(name: 'Jupiter', image: 'Jupiter', avatar: 'Jupiter',
      description: "Jupiter is the fifth planet from the Sun and the largest in the Solar System. A gas giant, "
          "Jupiter's mass is more than two and a half times that of all the other planets in the Solar System combined "
          "and slightly less than one one-thousandth the mass of the Sun. Jupiter orbits the Sun at a distance of 5.20 AU (778.5 Gm) "
          "with an orbital period of 11.86 years. It is the third brightest natural object in the Earth's night sky after the Moon "
          "and Venus and has been observed since prehistoric times. Its name derives from Jupiter, the chief deity of ancient Roman religion."
      "Jupiter was the first planet to form, and its inward migration during the primordial Solar System impacted much of the "
          "formation history of the other planets. Hydrogen constitutes 90% of Jupiter's volume, followed by helium, which forms 25% "
          "of its mass and 10% of its volume. The ongoing contraction of Jupiter's interior generates more heat than the planet receives "
          "from the Sun. Its internal structure is believed to consist of an outer mantle of fluid metallic hydrogen and a diffuse inner core "
          "of denser material. Because of its rapid rotation rate of one rotation per ten hours, Jupiter's shape is an oblate spheroid; it possesses "
          "a slight but noticeable bulge around the equator. The outer atmosphere is divided into a series of latitudinal bands, with turbulence and "
          "storms along their interacting boundaries. The most obvious result of this is the Great Red Spot, a giant storm that has been recorded since at least 1831."),
  Item(name: 'Saturn', image: 'Saturn', avatar: 'Saturn',
      description: "Saturn is the sixth planet from the Sun and the second-largest in the Solar System, after Jupiter. It is "
          "a gas giant with an average radius of about nine-and-a-half times that of Earth.[26][27] It has only one-eighth the "
          "average density of Earth, but is over 95 times more massive.[28][29][30] Even though Saturn is nearly the size of "
          "Jupiter, Saturn has less than one-third of Jupiter's mass. Saturn orbits the Sun at a distance of 9.59 AU (1,434 million "
          "km) with an orbital period of 29.45 years."
"Saturn's interior is thought to be composed of a rocky core, surrounded by a deep layer of metallic hydrogen, an intermediate "
          "layer of liquid hydrogen and liquid helium, and finally, a gaseous outer layer. Saturn has a pale yellow hue due to ammonia"
          " crystals in its upper atmosphere. An electrical current within the metallic hydrogen layer is thought to give rise to Saturn's "
          "planetary magnetic field, which is weaker than Earth's, but which has a magnetic moment 580 times that of Earth due to Saturn's larger"
          " size. Saturn's magnetic field strength is around one-twentieth of Jupiter's.[31] The outer atmosphere is generally bland and lacking"
          " in contrast, although long-lived features can appear. Wind speeds on Saturn can reach 1,800 kilometres per hour (1,100 miles per hour)."),
  Item(name: 'Uranus', image: 'Uranus', avatar: 'Uranus',
      description: "Uranus is the seventh planet from the Sun. It is a gaseous cyan-coloured ice giant. Most of the planet is "
          "made of water, ammonia, and methane in a supercritical phase of matter, which in astronomy is called 'ice' or "
          "volatiles. The planet's atmosphere has a complex layered cloud structure and has the lowest minimum temperature of "
          "49 K (−224 °C; −371 °F) out of all the Solar System's planets. It has a marked axial tilt of 82.23° with a retrograde "
          "rotation period of 17 hours and 14 minutes. This means that in an 84-Earth-year orbital period around the Sun, its poles "
          "get around 42 years of continuous sunlight, followed by 42 years of continuous darkness."
"Uranus has the third-largest diameter and fourth-largest mass among the Solar System's planets. Based on current models, inside its volatile"
          " mantle layer is a rocky core, and surrounding it is a thick hydrogen and helium atmosphere. Trace amounts of hydrocarbons (thought to"
          " be produced via hydrolysis) and carbon monoxide along with carbon dioxide (thought to have been originated from comets) have been detected "
          "in the upper atmosphere. There are many unexplained climate phenomena in Uranus's atmosphere, such as its peak wind speed of 900 km/h (560 mph),"
          "[22] variations in its polar cap, and its erratic cloud formation. The planet also has very low internal heat compared to other giant planets, the "
          "cause of which remains unclear."),
  Item(name: 'Neptune', image: 'Neptune', avatar: 'Neptune',
      description: "Neptune is the eighth and farthest known planet from the Sun. It is the fourth-largest planet in the Solar System by diameter, "
          "the third-most-massive planet, and the densest giant planet. It is 17 times the mass of Earth, and slightly more "
          "massive than fellow ice giant Uranus. Neptune is denser and physically smaller than Uranus because its greater mass "
          "causes more gravitational compression of its atmosphere. Being composed primarily of gases and liquids, it has no "
          "well-defined solid surface. The planet orbits the Sun once every 164.8 years at an orbital distance of 30.1 "
          "astronomical units (4.5 billion kilometres; 2.8 billion miles). It is named after the Roman god of the sea and has "
          "the astronomical symbol ♆, representing Neptune's trident.[f]"
"Neptune is not visible to the unaided eye and is the only planet in the Solar System that was found from mathematical predictions "
          "derived from indirect observations rather than being initially observed by direct empirical observation. Unexpected changes "
          "in the orbit of Uranus led Alexis Bouvard to hypothesise that its orbit was subject to gravitational perturbation by an unknown "
          "planet. After Bouvard's death, the position of Neptune was predicted from his observations, independently, by John Couch Adams and "
          "Urbain Le Verrier. Neptune was subsequently directly observed with a telescope on 23 September 1846[1] by Johann Gottfried Galle within "
          "a degree of the position predicted by Le Verrier. Its largest moon, Triton, was discovered shortly thereafter, though none of the planet's "
          "remaining 15 known moons were located telescopically until the 20th century. The planet's distance from Earth gives it a small apparent size,"
          " making it challenging to study with Earth-based telescopes. Neptune was visited by Voyager 2, when it flew by the planet on 25 August 1989; "
          "Voyager 2 remains the only spacecraft to have visited it.[18][19] The advent of the Hubble Space Telescope and large ground-based telescopes "
          "with adaptive optics has allowed for additional detailed observations from afar."),
];